[build]
functions = "functions"

[[redirects]]
to = "/pull2"
from = "/pull"
status = "301"

[[redirects]]
from = "/products/giftcard"
to = "/products/e-giftcard"
status = 301

[[redirects]]
from = "/sizing"
to = "/pages/sizing"
status = 301

[[redirects]]
from = "/reviews"
to = "/pages/reviews"
status = 301

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "."
  prettyURLs = true
  trailingSlash = true
