[build]
functions = "functions"

[[redirects]]
to = "/pages/phoebereads?utm_medium=podcast&utm_source=phoebereads&utm_campaign=fall2021&utm_content=30-prerecord"
from = "/phoebereads"
status = "301"

[[redirects]]
to = "/pages/busy20?utm_medium=podcast&utm_source=busy20&utm_campaign=fall2021&utm_content=igstory"
from = "/busy20"
status = "301"

[[redirects]]
from = "/collections/:collection/products/:product"
to = "/products/:product"
status = 301

[[redirects]]
from = "/products/giftcard"
to = "/products/e-giftcard"
status = 301

[[redirects]]
from = "/sizing"
to = "/pages/sizing"
status = 301

[[redirects]]
from = "/reviews"
to = "/pages/reviews"
status = 301

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "."
  prettyURLs = true
  trailingSlash = true
